name: mini_samples
description: Examples that teach the use of Dart through short, directed code snippets.
dependencies:
  angular: 0.14.0
  browser: any
  shadow_dom: any
  yaml: any
  polymer: any
dev_dependencies:
  unittest: any
dependency_overrides:
  html5lib: ">=0.12.0"
